version: '3.1'

services:
  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ex_mon_dev
    ports:
      - '5432:5432'
